### ISSUE TITLE
path error with -book=ward (but worm worked)

### ISSUE THREAD

**Issue by atomoton** [domenic/worm-scraper#29]
```
~/Downloads ⌚ 10:19:31
$ worm-scraper -book=ward
Downloading https://parahumans.wordpress.com/2013/11/19/interlude-end/... done
Converting raw downloaded HTML to EPUB chapters
All chapters converted in 23.4 seconds
EPUB contents assembled into /usr/lib/node_modules/worm-scraper/scaffolding
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received an instance of Array
    at validateString (internal/validators.js:124:11)
    at Object.resolve (path.js:980:7)
    at /usr/lib/node_modules/worm-scraper/lib/worm-scraper.js:105:58
    at /usr/lib/node_modules/worm-scraper/lib/worm-scraper.js:111:13
```

**Comment by domenic** [comment]
Try --book=ward?

**Comment by atomoton** [comment]
100% that works! Thank you, who knows how long I would have not noticed that.
